site_name: C3 Supercomputer
site_url: https://c3-uc3m.github.io/c3-web/

theme:
    name: material
    language: en
    logo: assets/images/C3_logo_white.png
    custom_dir: overrides
    features:
        # - navigation.footer
        - toc.follow
        - toc.integrate
        - content.code.copy

watch:
  - mkdocs.yml
  - docs/
  - overrides/

markdown_extensions:
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets

nav:
  - Home: index.md
  - Resources:
    - System Description: resources/system.md
    - Lustre Distributed Filesystem: resources/lustre.md
    - Slurm: resources/slurm.md
    - Installed Software: resources/installed_sw.md
  - Usage:
    - Cluster Access: user_docs/cluster_access.md
    - Slurm: user_docs/slurm.md
    - How to use Installed Software: user_docs/installed_sw.md
    - JupyterHub: user_docs/jupyter.md
    - Apptainer:
      - User Guide: user_docs/apptainer.md
      - Docker to Apptainer: user_docs/docker2apptainer.md
    - MATLAB: user_docs/matlab.md
    - Install Custom Software with Spack: user_docs/install_custom_sw_spack.md
    - Accounting: user_docs/accounting.md
  - HPC Courses: courses.md

extra_css:
  - stylesheets/extra.css
