site_name: C3 Supercomputer
site_url: https://c3-uc3m.github.io/c3-web/

theme:
    name: material
    language: en
    logo: assets/images/C3_logo_white.png
    custom_dir: overrides
    features:
        - toc.follow
        - toc.integrate
        - content.code.copy

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Welcome
        - Visit

watch:
  - mkdocs.yml
  - docs/
  - overrides/

markdown_extensions:
  - attr_list
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Request Access: cai.md
  - Resources:
    - System Description: resources/system.md
    - Data Storage: resources/storage.md
    - Slurm: resources/slurm.md
    - Installed Software: resources/installed_sw.md
  - Usage:
    - Cluster Access: user_docs/cluster_access.md
    - Slurm: user_docs/slurm.md
    - How to use Installed Software: user_docs/installed_sw.md
    - JupyterLab: user_docs/jupyter.md
    - Apptainer:
      - User Guide: user_docs/apptainer.md
      - Docker to Apptainer: user_docs/docker2apptainer.md
    - MATLAB: user_docs/matlab.md
    - Install Custom Software with Spack: user_docs/install_custom_sw_spack.md
    - Accounting: user_docs/accounting.md
  - News:
    - Blog: blog/index.md
  - Use cases: use_cases.md
  - HPC Courses: courses.md

extra_css:
  - stylesheets/extra.css
